from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import DataRequired, Length

class TeamsSearchForm(FlaskForm):
    yearID = IntegerField('Year ID', default=-1, render_kw={'placeholder': 'Enter the team\'s year ID'})
    leagueID = StringField('League ID', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s league ID'})
    teamID = StringField('Team ID', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s ID'})
    franchID = StringField('Franchise ID', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s franchise ID'})
    divID = StringField('Division ID', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s division ID'})
    rank = IntegerField('Rank', default=-1, render_kw={'placeholder': 'Enter the team\'s rank'})
    G = IntegerField('Games', default=-1, render_kw={'placeholder': 'Enter the team\'s total games'})
    Ghome = IntegerField('Games Played at Home', default=-1, render_kw={'placeholder': 'Enter the team\'s total home games'})
    W = IntegerField('Wins', default=-1, render_kw={'placeholder': 'Enter the team\'s total wins'})
    L = IntegerField('Losses', default=-1, render_kw={'placeholder': 'Enter the team\'s total losses'})
    DivWin = StringField('Division Winner', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s division win situation (Y/N)'})
    WCWin = StringField('Wild Card Winner', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s Wild Card win situation (Y/N)'})
    LgWin = StringField('League Champion', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s league championship situation (Y/N)'})
    WSWin = StringField('World Series Winner', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s World Series win situation (Y/N)'})
    R = IntegerField('Runs Scored', default=-1, render_kw={'placeholder': 'Enter the team\'s runs'})
    AB = IntegerField('At Bats', default=-1, render_kw={'placeholder': 'Enter the team\'s bats'})
    H = IntegerField('Hits by Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s hits'})
    twoB = IntegerField('Doubles', default=-1, render_kw={'placeholder': 'Enter the team\'s doubles'})
    threeB = IntegerField('Triples', default=-1, render_kw={'placeholder': 'Enter the team\'s triples'})
    HR = IntegerField('Homeruns by Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s homeruns'})
    BB = IntegerField('Walks by Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s walks'})
    SO = IntegerField('Strikeouts by Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s strikeouts'})
    SB = IntegerField('Stolen Bases', default=-1, render_kw={'placeholder': 'Enter the team\'s stolen bases'})
    CS = IntegerField('Caught Stealing', default=-1, render_kw={'placeholder': 'Enter the team\'s caught stealing'})
    HBP = IntegerField('Batters Hit by Pitch', default=-1, render_kw={'placeholder': 'Enter the team\'s batters hit by pitch'})
    SF = IntegerField('Sacrifice Flies', default=-1, render_kw={'placeholder': 'Enter the team\'s sacrifice flies'})
    RA = IntegerField('Opponent Runs Scored', default=-1, render_kw={'placeholder': 'Enter the team\'s opponent runs'})
    ER = IntegerField('Earned Runs Allowed', default=-1, render_kw={'placeholder': 'Enter the team\'s earned runs'})
    ERA = IntegerField('Earned Runs Average', default=-1, render_kw={'placeholder': 'Enter the team\'s earned runs average'})
    CG = IntegerField('Complete Games', default=-1, render_kw={'placeholder': 'Enter the team\'s complete games'})
    SHO = IntegerField('Shoutouts', default=-1, render_kw={'placeholder': 'Enter the team\'s shoutouts'})
    SV = IntegerField('Saves', default=-1, render_kw={'placeholder': 'Enter the team\'s saves'})
    IPOuts = IntegerField('Outs Pitched', default=-1, render_kw={'placeholder': 'Enter the team\'s pitched outs'})
    HA = IntegerField('Hits Allowed', default=-1, render_kw={'placeholder': 'Enter the team\'s allowed hits'})
    HRA = IntegerField('Homeruns Allowed', default=-1, render_kw={'placeholder': 'Enter the team\'s allowed homeruns'})
    BBA = IntegerField('Walks Allowed', default=-1, render_kw={'placeholder': 'Enter the team\'s allowed walks'})
    SOA = IntegerField('Strikeouts by Pitchers', default=-1, render_kw={'placeholder': 'Enter the team\'s strikeouts by pitchers'})
    E = IntegerField('Errors', default=-1, render_kw={'placeholder': 'Enter the team\'s errors'})
    DP = IntegerField('Double Plays', default=-1, render_kw={'placeholder': 'Enter the team\'s double plays'})
    FP = IntegerField('Fielding Percentage', default=-1, render_kw={'placeholder': 'Enter the team\'s fielding percentage'})
    name = StringField('Team Name', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s name'})
    park = StringField('Park Name', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s bullpark name'})
    attendance = IntegerField('Attendance', default=-1, render_kw={'placeholder': 'Enter the team\'s total home attendance'})
    BPF = IntegerField('Three Year Park Factor for Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s three year park factor for batters'})
    PPF = IntegerField('Three Year Park Factor for Pitchers', default=-1, render_kw={'placeholder': 'Enter the team\'s three year park factor for pitchers'})
    teamIDBR = StringField('TeamID Used by Baseball Reference Website', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s teamID used by baseball reference website'})
    teamIDlahman45 = StringField('TeamID Used by Lahman Database', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s teamID used by Lahman Database'})
    teamIDretro = StringField('TeamID Used by Retrosheet', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s teamID used by Retrosheet'})

    submit = SubmitField('Search', render_kw={'class': 'btn btn-outline-secondary'})



class TeamsInsertionForm(FlaskForm):
    yearID = IntegerField('Year ID', default=-1, render_kw={'placeholder': 'Enter the team\'s year ID'})
    leagueID = StringField('League ID', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s league ID'})
    teamID = StringField('Team ID', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s ID'})
    franchID = StringField('Franchise ID', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s franchise ID'})
    divID = StringField('Division ID', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s division ID'})
    rank = IntegerField('Rank', default=-1, render_kw={'placeholder': 'Enter the team\'s rank'})
    G = IntegerField('Games', default=-1, render_kw={'placeholder': 'Enter the team\'s total games'})
    Ghome = IntegerField('Games Played at Home', default=-1, render_kw={'placeholder': 'Enter the team\'s total home games'})
    W = IntegerField('Wins', default=-1, render_kw={'placeholder': 'Enter the team\'s total wins'})
    L = IntegerField('Losses', default=-1, render_kw={'placeholder': 'Enter the team\'s total losses'})
    DivWin = StringField('Division Winner', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s division win situation (Y/N)'})
    WCWin = StringField('Wild Card Winner', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s Wild Card win situation (Y/N)'})
    LgWin = StringField('League Champion', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s league championship situation (Y/N)'})
    WSWin = StringField('World Series Winner', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s World Series win situation (Y/N)'})
    R = IntegerField('Runs Scored', default=-1, render_kw={'placeholder': 'Enter the team\'s runs'})
    AB = IntegerField('At Bats', default=-1, render_kw={'placeholder': 'Enter the team\'s bats'})
    H = IntegerField('Hits by Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s hits'})
    twoB = IntegerField('Doubles', default=-1, render_kw={'placeholder': 'Enter the team\'s doubles'})
    threeB = IntegerField('Triples', default=-1, render_kw={'placeholder': 'Enter the team\'s triples'})
    HR = IntegerField('Homeruns by Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s homeruns'})
    BB = IntegerField('Walks by Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s walks'})
    SO = IntegerField('Strikeouts by Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s strikeouts'})
    SB = IntegerField('Stolen Bases', default=-1, render_kw={'placeholder': 'Enter the team\'s stolen bases'})
    CS = IntegerField('Caught Stealing', default=-1, render_kw={'placeholder': 'Enter the team\'s caught stealing'})
    HBP = IntegerField('Batters Hit by Pitch', default=-1, render_kw={'placeholder': 'Enter the team\'s batters hit by pitch'})
    SF = IntegerField('Sacrifice Flies', default=-1, render_kw={'placeholder': 'Enter the team\'s sacrifice flies'})
    RA = IntegerField('Opponent Runs Scored', default=-1, render_kw={'placeholder': 'Enter the team\'s opponent runs'})
    ER = IntegerField('Earned Runs Allowed', default=-1, render_kw={'placeholder': 'Enter the team\'s earned runs'})
    ERA = IntegerField('Earned Runs Average', default=-1, render_kw={'placeholder': 'Enter the team\'s earned runs average'})
    CG = IntegerField('Complete Games', default=-1, render_kw={'placeholder': 'Enter the team\'s complete games'})
    SHO = IntegerField('Shoutouts', default=-1, render_kw={'placeholder': 'Enter the team\'s shoutouts'})
    SV = IntegerField('Saves', default=-1, render_kw={'placeholder': 'Enter the team\'s saves'})
    IPOuts = IntegerField('Outs Pitched', default=-1, render_kw={'placeholder': 'Enter the team\'s pitched outs'})
    HA = IntegerField('Hits Allowed', default=-1, render_kw={'placeholder': 'Enter the team\'s allowed hits'})
    HRA = IntegerField('Homeruns Allowed', default=-1, render_kw={'placeholder': 'Enter the team\'s allowed homeruns'})
    BBA = IntegerField('Walks Allowed', default=-1, render_kw={'placeholder': 'Enter the team\'s allowed walks'})
    SOA = IntegerField('Strikeouts by Pitchers', default=-1, render_kw={'placeholder': 'Enter the team\'s strikeouts by pitchers'})
    E = IntegerField('Errors', default=-1, render_kw={'placeholder': 'Enter the team\'s errors'})
    DP = IntegerField('Double Plays', default=-1, render_kw={'placeholder': 'Enter the team\'s double plays'})
    FP = IntegerField('Fielding Percentage', default=-1, render_kw={'placeholder': 'Enter the team\'s fielding percentage'})
    name = StringField('Team Name', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s name'})
    park = StringField('Park Name', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s bullpark name'})
    attendance = IntegerField('Attendance', default=-1, render_kw={'placeholder': 'Enter the team\'s total home attendance'})
    BPF = IntegerField('Three Year Park Factor for Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s three year park factor for batters'})
    PPF = IntegerField('Three Year Park Factor for Pitchers', default=-1, render_kw={'placeholder': 'Enter the team\'s three year park factor for pitchers'})
    teamIDBR = StringField('TeamID Used by Baseball Reference Website', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s teamID used by baseball reference website'})
    teamIDlahman45 = StringField('TeamID Used by Lahman Database', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s teamID used by Lahman Database'})
    teamIDretro = StringField('TeamID Used by Retrosheet', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s teamID used by Retrosheet'})

    submit = SubmitField('Insert', render_kw={'class': 'btn btn-outline-secondary'})

class TeamsUpdateForm(FlaskForm):
    yearID = IntegerField('Year ID', default=-1, render_kw={'placeholder': 'Enter the team\'s year ID'})
    leagueID = StringField('League ID', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s league ID'})
    teamID = StringField('Team ID', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s ID'})
    franchID = StringField('Franchise ID', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s franchise ID'})
    divID = StringField('Division ID', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s division ID'})
    rank = IntegerField('Rank', default=-1, render_kw={'placeholder': 'Enter the team\'s rank'})
    G = IntegerField('Games', default=-1, render_kw={'placeholder': 'Enter the team\'s total games'})
    Ghome = IntegerField('Games Played at Home', default=-1, render_kw={'placeholder': 'Enter the team\'s total home games'})
    W = IntegerField('Wins', default=-1, render_kw={'placeholder': 'Enter the team\'s total wins'})
    L = IntegerField('Losses', default=-1, render_kw={'placeholder': 'Enter the team\'s total losses'})
    DivWin = StringField('Division Winner', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s division win situation (Y/N)'})
    WCWin = StringField('Wild Card Winner', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s Wild Card win situation (Y/N)'})
    LgWin = StringField('League Champion', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s league championship situation (Y/N)'})
    WSWin = StringField('World Series Winner', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s World Series win situation (Y/N)'})
    R = IntegerField('Runs Scored', default=-1, render_kw={'placeholder': 'Enter the team\'s runs'})
    AB = IntegerField('At Bats', default=-1, render_kw={'placeholder': 'Enter the team\'s bats'})
    H = IntegerField('Hits by Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s hits'})
    twoB = IntegerField('Doubles', default=-1, render_kw={'placeholder': 'Enter the team\'s doubles'})
    threeB = IntegerField('Triples', default=-1, render_kw={'placeholder': 'Enter the team\'s triples'})
    HR = IntegerField('Homeruns by Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s homeruns'})
    BB = IntegerField('Walks by Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s walks'})
    SO = IntegerField('Strikeouts by Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s strikeouts'})
    SB = IntegerField('Stolen Bases', default=-1, render_kw={'placeholder': 'Enter the team\'s stolen bases'})
    CS = IntegerField('Caught Stealing', default=-1, render_kw={'placeholder': 'Enter the team\'s caught stealing'})
    HBP = IntegerField('Batters Hit by Pitch', default=-1, render_kw={'placeholder': 'Enter the team\'s batters hit by pitch'})
    SF = IntegerField('Sacrifice Flies', default=-1, render_kw={'placeholder': 'Enter the team\'s sacrifice flies'})
    RA = IntegerField('Opponent Runs Scored', default=-1, render_kw={'placeholder': 'Enter the team\'s opponent runs'})
    ER = IntegerField('Earned Runs Allowed', default=-1, render_kw={'placeholder': 'Enter the team\'s earned runs'})
    ERA = IntegerField('Earned Runs Average', default=-1, render_kw={'placeholder': 'Enter the team\'s earned runs average'})
    CG = IntegerField('Complete Games', default=-1, render_kw={'placeholder': 'Enter the team\'s complete games'})
    SHO = IntegerField('Shoutouts', default=-1, render_kw={'placeholder': 'Enter the team\'s shoutouts'})
    SV = IntegerField('Saves', default=-1, render_kw={'placeholder': 'Enter the team\'s saves'})
    IPOuts = IntegerField('Outs Pitched', default=-1, render_kw={'placeholder': 'Enter the team\'s pitched outs'})
    HA = IntegerField('Hits Allowed', default=-1, render_kw={'placeholder': 'Enter the team\'s allowed hits'})
    HRA = IntegerField('Homeruns Allowed', default=-1, render_kw={'placeholder': 'Enter the team\'s allowed homeruns'})
    BBA = IntegerField('Walks Allowed', default=-1, render_kw={'placeholder': 'Enter the team\'s allowed walks'})
    SOA = IntegerField('Strikeouts by Pitchers', default=-1, render_kw={'placeholder': 'Enter the team\'s strikeouts by pitchers'})
    E = IntegerField('Errors', default=-1, render_kw={'placeholder': 'Enter the team\'s errors'})
    DP = IntegerField('Double Plays', default=-1, render_kw={'placeholder': 'Enter the team\'s double plays'})
    FP = IntegerField('Fielding Percentage', default=-1, render_kw={'placeholder': 'Enter the team\'s fielding percentage'})
    name = StringField('Team Name', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s name'})
    park = StringField('Park Name', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s bullpark name'})
    attendance = IntegerField('Attendance', default=-1, render_kw={'placeholder': 'Enter the team\'s total home attendance'})
    BPF = IntegerField('Three Year Park Factor for Batters', default=-1, render_kw={'placeholder': 'Enter the team\'s three year park factor for batters'})
    PPF = IntegerField('Three Year Park Factor for Pitchers', default=-1, render_kw={'placeholder': 'Enter the team\'s three year park factor for pitchers'})
    teamIDBR = StringField('TeamID Used by Baseball Reference Website', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s teamID used by baseball reference website'})
    teamIDlahman45 = StringField('TeamID Used by Lahman Database', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s teamID used by Lahman Database'})
    teamIDretro = StringField('TeamID Used by Retrosheet', [Length(max=100)], default="", render_kw={'placeholder': 'Enter the team\'s teamID used by Retrosheet'})

    submit = SubmitField('Update', render_kw={'class': 'btn btn-outline-secondary'})